### ISSUE TITLE
Multiple initial values for ode

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#105]
Motivations:
--------------
* PR #104 introduced the possibility of setting multiple values to fixed parameters
* It let the user choose whether he wants a systematic exploration of all combinations of values (`grid=True`) or to pick only cases of interest (`grid=False`, default)
* The same would be useful for initial values of `ode`

Proposition:
--------------
* Implement the possibility of setting multiple values for initial values of lde (using arrays)
* It will probably imply small modifications of attribute `Hub.dmisc['dmulti']`
* Make the `grid` option more flexible:
    - now it's either `grid=True` for all or `grid=False` for all
    - It would be nice if the user could choose to set `grid=True` just for some parameters / initial values he picks. This would allow to combine cherry-picking of cases of interest with systematic exploration of some parameters only.

**Comment by DaluS** [comment]
It'd be very practical to have the ODE initial conditions indeed ! 

I think the grid is not too important (compared to multisectorial/EDP) but if it's rapid for you to implement that's a good enhancement
