### ISSUE TITLE
Code clean-up and simplifications

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#107]
Motivations:
--------------
* We now have a running code, and it is slowly getting more and more mature
* As it matures, we can start identifying small changes that could make it easier to maintain / develop, or that could simplify it or make it more straightforward
* Based on my development experience from the last weeks, this a small non-exhaustive list of small changes that would out life easier at developping / maintaining.
* I will gradually list here all small changes I identify as I code
* Please comment below so we can decide together

Reserved keywords avoidance:
----------------------------------

### lambda
`lambda` is a common variable in macro-economic models
It is also a reserved name in python (for anonymous functions)

When the user defines an anonymous function that depends on `lambda`, there is a name conflict, it is not possible to write

![image](https://user-images.githubusercontent.com/5929562/131649622-3c2d509f-53c9-478b-a74c-3d4f90320fcb.png)

So far, this has been circumvented by using lamb instead of lambda in such case (in the keywaord args of functions.
It works, but it introduces significant hassle because it forces the developper to always treat lmabda as an exception and to implement if statements to treat it separately

This has slowed down development and made it more difficult (if you forget to treat that exception the code fails and you have to understand why).

A very simple fix that would simplify the code and development would be to uniformize the keyword argument and the dict key as lamb, so routines can treat it like any other variable and automatically associate the keyword arg with the dict key.
The full name lambdac an still be stored under the symbol field, which is to be used for plots, this way plots would still display lambda, but the developer's life (and the code) would be made non-negligibly simpler.

Replace this:
![image](https://user-images.githubusercontent.com/5929562/131650676-39fdb41c-c8c5-4600-958b-d0a1acf0a9de.png)

by this:
![image](https://user-images.githubusercontent.com/5929562/131650591-29ca75b7-ede9-48ff-b05c-f43e82cd523e.png)

File / models naming:
-----------------------
* According to PEP8 conventions, most variable and function names in python have to be minor case and words separated by underscores
* In the same spirit, we are currently using underscores to separate the various parts of an output file name (and even of module names)
* This allows for easy parsing of the file names to extract the relevant info
* But it only works fine if each part of the name does not itself have an underscore
* For example, the non-regression files are stored as:
![image](https://user-images.githubusercontent.com/5929562/131655374-eb5ccd43-d139-437c-884a-08813f85904e.png)

This was already discussed in PR #62: the saved files have structure:

`Output_model_preset_solver_<custom-name-from-user>_user_date_time.npz`

Hence a problem arises with model `G_Reduced`, because it has an underscore in its name, which breaks the automation and forces us to implement caveats and special treatments for that case to replace the underscore by a dash.

A simple fix to simplify the code would be to adopt the following convention:
* model, preset, solver and custom name should not include underscores  `_` or spaces ` `
* separations can be done by dashes `-`

`G_Reduced` <=> `G-Reduced`

If adopted, this convention should be applyed to all future models / presets / solvers / custom names.
What do you think ?

**Comment by DaluS** [comment]
I agree with all these conventions, I'll in the future readme put a special part for the `lamb` case. maybe instead of `lamb`, `employment` as a full name will might be more useful...

**Comment by DaluS** [comment]
Pretty much cleaned !
