### ISSUE TITLE
get_dparam_as_reverse_dict with multiple criterias ?

### ISSUE THREAD

**Issue by DaluS** [DaluS/GEMMES#109]
One of the main use of `hub.get_dparam_as_reverse_dict` in the current use is to give all variables that share he same units.

It is easy to get all the variables at the same time ( `hub.get_dparam_as_reverse_dict(crit='eqtype') ` ) or get all the fields with the same dimensions ( `hub.get_dparam_as_reverse_dict(crit='units')` ) however, getting both of them at the same time is not possible. 

A way to obtain it : 

`groupsoffields = hub.get_dparam_as_reverse_dict(crit='units')`

`groupsofvariables = { k : [v for v in vals if v in hub.dargs.keys() ] for k,vals in groupsoffields.items()}`

Should we wrap this around a function or just keep it that way ?

**Comment by Didou09** [comment]
Hi !

Just to be sure I understand your need: when you say "both at the same time", did you try it this way:

```
In [1]: import pygemmes as pgm                                                                                                                                                         

In [2]: hub = pgm.Hub('GK', preset='default')  

In [3]:  dout = hub.get_dparam_as_reverse_dict(crit='eqtype', units='$') 

In [4]: dout                                                                                                                                                                           
Out[4]: {'ode': ['D', 'W'], 'param': [], 'statevar': ['GDP', 'Pi', 'I'], None: []}
```

* `crit` is the name of the field that will be used for sorting the output dict 
* Any other field can be provided as input, for selection (except the one used for `crit`)

```
In [5]: dout = hub.get_dparam_as_reverse_dict(crit='eqtype', units=['$', 'undefined'], group='CORE')                                                                                   

In [6]: dout                                                                                                                                                                          
Out[6]: 
{'ode': ['W'],
 'param': [],
 'statevar': ['Pi', 'lambda', 'omega', 'I', 'pi'],
 None: ['nu']}
```

**Comment by DaluS** [comment]
What I mean by both is :
* The dictionary is based on the crit (in term of keys), in this case `units`
* The content of each definition is filtered by another one, in this case `eqtype!=parameters` 

Here is an example : 

`groupsoffields
Out[36]: 
{'undefined': ['lambda',
  'omega',
  'd',
  'kappa',
  'pi',
  'nt',
  'gamma',
  'k0',
  'k1',
  'k2',
  'mu',
  'phinull',
  'phi0',
  'phi1'],
 'y^{-1}': ['phillips',
  'inflation',
  'g',
  'alpha',
  'beta',
  'delta',
  'r',
  'etaprice'],
 '$': ['p'],
 'y': ['Tmax', 'dt', 'nx', 'time', 'nu']}`

Gives you by units both parameters and variables 

`groupsofvariables = { k : [v for v in vals if v in hub.dargs.keys() ] for k,vals in groupsoffields.items()}
Out[35]: 
{'undefined': ['lambda', 'omega', 'd', 'kappa', 'pi'],
 'y^{-1}': ['phillips', 'inflation', 'g'],
 '$': ['p'],
 'y': ['time']}`

Gives what I was looking for ! 
Honestly it a miscellaneous thing that can be solved with a one-liner, just curious if there was any direct call to do it

**Comment by Didou09** [comment]
I might be mistaken but the command already does exactly this

`In [5]: dout = hub.get_dparam_as_reverse_dict(crit='units', eqtype=None) `

Will return a duct sorted by units (crit=units) taking into account only fixed value parameters (eqtype=None)

On the opposite, using a tuple as input, the following will do the same but this time taking into account everything except fixed value parameters

`In [5]: dout = hub.get_dparam_as_reverse_dict(crit='units', eqtype=(None,))`

**Comment by DaluS** [comment]
Fantastic ! I did not understood that method to either include or exclude, that's quite handy thanks !
