### ISSUE TITLE
Regression detected

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#128]
During PR #116, a [regression](https://github.com/DaluS/GEMMES/pull/116#issuecomment-1005596144) was detected on the following models_presets_solvers:
* LorenzSystem_Canonical_eRK8-scipy
* DampOscillator_Perfect_eRK2-scipy
* LorenzSystem_Canonical_eRK4-scipy
 
![image](https://user-images.githubusercontent.com/5929562/148213239-655530c0-ba4d-4580-9376-66246ad6050f.png)

I first thought it came from a different environment, I ceated on my pc the same environment as the GA testing robots to produce the reference data, but the regression remains. A discussion with a specialist might help (investigate compilation differences ?)

**Comment by DaluS** [comment]
Posted a track here 
https://github.com/DaluS/GEMMES/pull/116#issuecomment-1005761081

**Comment by DaluS** [comment]
Solved in #130 !
