### ISSUE TITLE
List dependencies

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#13]
Motivation:
-------------
* On the long way to making a piece of code a proper library, one of the necessary steps is to identify all dependencies (all libraries on which the code depends)
* They should be listed in a `requirements.txt` file (see example in [tofu](https://github.com/ToFuProject/tofu/blob/devel/requirements.txt))
* This will be useful to complete the automated unit tests with Github (cf. PR #12 )

@DaluS could you try to list all libraries imported in the code ?
All libraries that are in [Python Standard library](https://docs.python.org/3/library/index.html) do not need to be listed, only the ones which are not automatically included in Python and need to be installed separately 5like numpy typically).

**Comment by DaluS** [comment]
The list now exist as requirement.txt ( I guess you created it ) and has no other external libraries last time I checked
