### ISSUE TITLE
Local user-defined models and _LIBRARY

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#132]
Motivations:
----------------
* A non-developer user may want to had models without having to git/commit anything to pygemms and github, either for temporary tests, play models, or non-public models (models he/she does not want to be open-source)
* This possibility would make it easier for @DaluS and @guittcam to play with pygemmes without having to modify the core

Proposition:
----------------
* A classic way to do it is to automatically create a .pygemmes/ folder in the user's home repo were he/she can edit private files at will. This is very similar to what ipython, matplotlib and other libraries do to enable user-defined configuration cusomizations
* The .pygemmes/ private folder will be automatically created at import time (if it does not exist already)
* The .pygemmes/ private folder, if it exists, will always be checked first by the code before using the default files (high-priority order)

This will be addressed in the next PR

**Comment by DaluS** [comment]
Excellent idea, I see that you already pushed this !
