### ISSUE TITLE
Article figures reproduction

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#134]
Motivations:
----------------
* As pointed out already in several issues, and in PR #129, one of the prerequisites of pygemmes is to be able to reproduce some classic figures from various chosen papers
* Most of the preparatory work has been done already by implementing the models formalisms and the presets.

Proposition:
---------------
* In the end, pygemmes should be able to reproduce, on-demand a large number of papers and figures
* In order to prepare for this and make it easily accessible to the user, I suggest to implement a formalism similar to models / presets and building on it
* I am only adressing the core code structure to make that easy to read / execute, not the models themselves.

In the same spirit of what we've done already, I propose to implement something like:

A tool similar to get_available_models() and get_available_solvers()... that will  print a list of the articles figures that can easily be reproduced by pygemmes
![image](https://user-images.githubusercontent.com/5929562/148555738-4378f24c-e27b-45a9-92b5-a72432b4dca5.png)

A single function call that will actually run the reproduction and print the desired figures and compare them with a png of the original
![image](https://user-images.githubusercontent.com/5929562/148556043-1f3c965c-0acc-4d9c-b97a-c1e8f175862c.png)

All the complexity is already stored in the model files and preset (@guittcam 's work if I understood correctly), that this routine will call.
The plotting routines can be developped in a dedicated Cockpit until they stabilized and validated and included directly in the core.

I will propose today a first implementation that we can discuss afterwards,
I can also propose to assist @guittcam on the implementaion in necessary

**Comment by DaluS** [comment]
I like the idea !

An article has often few (2-3) models inside it with each a few (2-3 again) figures. There should in consequence be a dictionary "articles" with the following architectures : 
articles = {1 name_of_the_article : {2 name_of_the_model : {3 name_of_the_preset ,} } }

I think this step will not be too harsh, as long as the "plot" section of presets is efficient. And for the moment I do not know which formalism to use (see #118 )

**Comment by Didou09** [comment]
Fixed, see PR #136
