### ISSUE TITLE
[#00014] Complete variable dictionnary

### ISSUE THREAD

**Issue by DaluS** [DaluS/GEMMES#14]
Remove blanks in the dictionnary of parameters

**Comment by DaluS** [comment]
@Didou09 done in #18  in fact

**Comment by Didou09** [comment]
Yes, but we cannot merge #18 because other changes caused a bug, would have been better practice to do this a dedicated branch and PR. Any chance you can split #18 into 4 separate PR ?

**Comment by DaluS** [comment]
I think the issue is solved ! Now I will check if models run as intended
