### ISSUE TITLE
[#015] Utils in another file ? 

### ISSUE THREAD

**Issue by DaluS** [DaluS/GEMMES#15]
Can we move the utility functions ( check params etc ) in another file to keep only the main and run in the main.py ? I saw that it could raise argparser errors so not sure if moving it would damage the structure or not

**Comment by Didou09** [comment]
Yes, we can, we just have to do it carefully (always make sure we avoid circular import dependencies)
I can do it or you can try, (on a dedicated branch as always), as you like

**Comment by DaluS** [comment]
Tried to do it but I had to put global variable or redefine functions : so I kept it as it is !

**Comment by DaluS** [comment]
Done in #28
