### ISSUE TITLE
Some issues after implementation of Coping 2018

### ISSUE THREAD

**Issue by chevaldemetal** [DaluS/GEMMES#159]
There is a problem when using get_available_models: _model_CamilleMines.py /_model_Camille_Mines.py. Choose one of them.

The main function descriptions must have the types of arguments explicitly given. Inputs and outputs could be precised.

Clean of variables in "_def_fields.py" must be regularly done to be sure there is no several definition of same things.

**Comment by DaluS** [comment]
implemented in #158
