### ISSUE TITLE
Automated syntax checking

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#17]
@DaluS , to start implementing automated syntax checking on all Pull Requests, go there:
https://github.com/apps/pep8-speaks

Click on Configure and add your repo with read access for pep8-speak:

![image](https://user-images.githubusercontent.com/5929562/124127053-9163c700-da7b-11eb-92c8-3455145b0131.png)

**Comment by DaluS** [comment]
That should work now !

**Comment by Didou09** [comment]
For a yet unknown reason, the syntax checking does not seem to have worked for the last PR, that may require some investigating

**Comment by DaluS** [comment]
It is working now, so I close this
