### ISSUE TITLE
pygemmes import issue

### ISSUE THREAD

**Issue by guittcam** [DaluS/GEMMES#170]
pygemmes cannot be imported correctly because of the lack of `pygemmes._plots._plot_tools` module. See screenshot below:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/86613124/163608072-700ee665-6be3-4ffd-b4b9-6a61c56eddb1.png">

**Comment by DaluS** [comment]
HI @guittcam which branch is it ?

**Comment by guittcam** [comment]
> HI @guittcam which branch is it ?

Hi @DaluS,  I had it for MATERCoupling, which depends on devel. It seems the issue is solved now.

<img width="368" alt="image" src="https://user-images.githubusercontent.com/86613124/164053950-7dbf6b40-0955-4cc8-a2f4-ee76c240f33c.png">

**Comment by DaluS** [comment]
Ok weird, it seems there was no push on this branch before or after (last version was 27 days ago) so I guess it was on your side. Happy to hear that it works !
