### ISSUE TITLE
Units /dimensions / symbols consistency

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#25]
After PR #24, the parameters in _def_parameters have all requested fields (let me know if you need more).

However, we notice that:
* all `units` are not consistent (`y^-1` vs `y^{-1}`, and maybe others
* some `units` may still be missing
* It would probably be good to fill in  all `dimensions` too
* It would probably be good to double-check all `symbols `too (I did my best from the parameters names)
* It would probably be good to fill in `names` (short `names` vs long `comments`)

**Comment by DaluS** [comment]
I included it my version of #24 ! 
A few comments : 
* I think latex formalism for unit is practical (maybe we should put it in r'$ $ everytime ?)
* Dimensions looked good enough for the moment, it'll be useful to come back to them once we plot them (that'll be much more practical) 
* I updated all symbols 
* I think names are too redundant to be kept ( symbol and comments already cover the use)

**Comment by Didou09** [comment]
I am temporarily re-opening this issue because of the following inconsistency in nomenclature I found:
* `phillips` is sometimes noted with 2 'l' (`phillips`), sometimes, with one (`philips`)

Which one shall we use?

**Comment by Didou09** [comment]
There is also this circular dependency I found in `SystemOfEquations/G_Reduced.py` while I was trying to keep up with the last changes before the fusion of the new `Solver` class:
![image](https://user-images.githubusercontent.com/5929562/124964112-ec1f9480-e020-11eb-8caf-bb321c5bde1d.png)

Here the function `omega` depends on itself, or a parameter with the same name, 
If possible I would recommend to make sure all parameters and functions have unique names, to avoid all possible confusions.
If these are really 2 different things, maybe `omega0` or `omega_scalar` could replace the fixed-value parameter name?
Otherwise, if this is a typo what is the correct parameter to use ?

**Comment by Didou09** [comment]
Same problem here:
![image](https://user-images.githubusercontent.com/5929562/124978167-b46d1880-e031-11eb-9d1d-89806a5a38ce.png)

**Comment by DaluS** [comment]
It's Phillips ! I corrected it everywhere
