### ISSUE TITLE
Decide the list of necessary fields in `_def_fields.py`

### ISSUE THREAD

**Issue by DaluS** [DaluS/GEMMES#47]
## Actual situation 

6 Mandatory fields :  
*    'value'    :  The basic value of the field. Can be a function, a float, an int
*    'com'      :  A commentary to explain its signification
*    'dimension' : The litteral physical dimension of the variable
*    'units'    : The units of the physical dimension
*    'type'     : If the variable is intensive, extensive, or dimensionless
*    'group'    : A classification of fields within subgroup (population, money...)
*    'symbol'  : The latex writing of the variable 

## What I think about it

1. Dimension is the litteral version of units and should be removed
2. type is not that useful (dimensionless is deduced from having no type, extensive variable have only one unit at the numerator) and can be deduced from the unit. No need for the user to define it.
3. 'com' and symbol are not necessary (but welcome)
4. What is exactly in groups is not clear. I think this should be either linked to : 
* The equation they are typically in
* The article / user that introduced them

## What we should we do ? 

I think : 
* Remove dimension and type for the moment (they are not used anyway but in checks)
* Define a proper list of group 
* Add an ensemble of functions that help us : 
    * If there is no field `com` replace it by ''
    * If there is no field `symbol` replace it by the key 
    * If there is no field `group` replace it by no group (and raise warning)
    * If there is no field `value` then it's a none (and raise a warning as some system might force it ? Typically the simplest function for intermediary variables)
    * Check that the `units` are a combination of known units in the system 
    * Deduce if the variable is intensive/extensive/dimensionless from the units (add the type field in consequence) 
    * Deduce from the model loaded if the field is a variable (which type) or a parameter or nothing

In consequence the only thing a user has to give is the name and the units ! A true model of physicist that will terrify economist (gosh, units with my variables ?! ) for the best :D 

## What is (still for me) unclear ?
 
 * Groups ! What choice we do is important in term of classification.

**Comment by Didou09** [comment]
Agreed, all of this is important,

Some comments:
* Non-necessary fields (dimension, ...) since we already have them I suggest we keep them and wait before removing them (from experience, we might want to re-add them later), we can just de-activate the checks and rigidity around them


> Check that the units are a combination of known units in the system

This requires defining a list of known units (USI ?), and will probably require its own issue / PR

> Groups ! What choice we do is important in term of classification.

_Random ideas:_
Maybe we could define several types of groups (group, category, type, ... or group0, group1, group2...) ?
Or group variables by theme (economy, climate...) and put all coupling variables in a separate 'coupling'  group ?
Or use this to identify (automatically) stocks vs flux ?

**Comment by DaluS** [comment]
> * Non-necessary fields (dimension, ...) since we already have them I suggest we keep them and wait before removing them (from experience, we might want to re-add them later), we can just de-activate the checks and rigidity around them

Ok ! We will see if on the long run we don't need them (and in that case I'll remove them in a few months), we can comment them for the moment simply 

> > Check that the units are a combination of known units in the system
> This requires defining a list of known units (USI ?), and will probably require its own issue / PR

Yes we could do that ! For the moment no need to hurry about this implementation, the name of variables is in fact enough for the type of users we have :) 

> _Random ideas:_
> Maybe we could define several types of groups (group, category, type, ... or group0, group1, group2...) ?
> Or group variables by theme (economy, climate...) and put all coupling variables in a separate 'coupling' group ?
> Or use this to identify (automatically) stocks vs flux ?

I see your point and I find it an interesting approach, however it would add more things to add which I find less practical. 
Maybe something that could work, would be to give user freedom on these groups ? An idea I had was that : 
* `_DFIELD` is transformed into a dictA{ dictC { dictB}}}. (instead of a dictA{ dictB{ }}), and the dictC correspond to the groups ! dictB still contains the field as before). We just have to check that there is no the same key defined in multiple groups (which should be easy to do). 

The advantages : 
* A group is by nature grouped like this (easy to find) 
* Code folding is much more practical
* The organisation of group is for the user to find its way in the jungle mostly, so if a group is defined as Paul : { } or ClimateModel : { } and both coexist I think that's fine

**Comment by DaluS** [comment]
> * Non-necessary fields (dimension, ...) since we already have them I suggest we keep them and wait before removing them (from experience, we might want to re-add them later), we can just de-activate the checks and rigidity around them

Ok ! We will see if on the long run we don't need them (and in that case I'll remove them in a few months), we can comment them for the moment simply 

> > Check that the units are a combination of known units in the system
> This requires defining a list of known units (USI ?), and will probably require its own issue / PR

Yes we could do that ! For the moment no need to hurry about this implementation, the name of variables is in fact enough for the type of users we have :) 

> _Random ideas:_
> Maybe we could define several types of groups (group, category, type, ... or group0, group1, group2...) ?
> Or group variables by theme (economy, climate...) and put all coupling variables in a separate 'coupling' group ?
> Or use this to identify (automatically) stocks vs flux ?

I see your point and I find it an interesting approach, however it would add more things to add which I find less practical. 
Maybe something that could work, would be to give user freedom on these groups ? An idea I had was that : 
* `_DFIELD` is transformed into a dictA{ dictC { dictB}}}. (instead of a dictA{ dictB{ }}), and the dictC correspond to the groups ! dictB still contains the field as before). We just have to check that there is no the same key defined in multiple groups (which should be easy to do). 

The advantages : 
* A group is by nature grouped like this (easy to find) 
* Code folding is much more practical
* The organisation of group is for the user to find its way in the jungle mostly, so if a group is defined as Paul : { } or ClimateModel : { } and both coexist I think that's fine 


---------------------

I think I can add the discussion here for ODE initial condition as it touches the same files. My proposition (I'm not sure it's the best one for sure) : 

the 'basic' initial condition is stored as a value in `_DFIELDS`, the function that makes it move is in the model. When loading an ode in the model, the code will indeed move the value of _DFIELDS in initial condition, and replace the value by the function (which could reduce the general tests one could do of the model, but I'm not sure it's critical) 

Why ? Two reason mostly : 
* It allows information to be at one place, without adding any definition field, that still have a logical overload order (all the default values are at the same place, all the preset of a model are inside the same model) 
* To understand the signification, let's say that a parameter is a statue : an appearance well defined, unmovable. When the model is load, associating an ODE to the field is giving him his own behavior : it keeps his nature, but he'll be able to change it according to the behavior we add. 

I think that makes sense like this, but I'm telling me stories taking advantage of by tired friday brain... What do you think about it @didou09 ?

**Comment by Didou09** [comment]
> the 'basic' initial condition is stored as a value in _DFIELDS, the function that makes it move is in the model. When loading an ode in the model, the code will indeed move the value of _DFIELDS in initial condition, and replace the value by the function (which could reduce the general tests one could do of the model, but I'm not sure it's critical)

hum, I'm not sure,
it means every time the user will want to change the initial value he/she will have to edit `_def_fields.py`, which is not in the same place as the function itself.
That may be a problem for example if the user wants to run 2 different models using the same quantities, if they both have to read the initial value from `_def_fields.py`, it makes it more complicated to set different initial values.

I might be wrong but I had in mind that the user would only edit the `_model_Name.py` file (because that's where they will define their own models, functions... and the presets of parameters, which can hold the initial value too), and never edit the `_def_fields.py` file, which is primarily there for defining the default units, groups, dimensions, comments, symbols so the users don't have to re-write them for every model.
These are generic fields that don't change and that can be stored as default.
The initial value (or the fixed value) of a parameter is something much less generic / much more prone to be modified by the user. I think the user should have to it in a place like `_model_name.py` that the user can edit (if they define their own models they will edit the model file). 

Also I think it is a bit a bit dangerous to use the same name 'value' for different things:
* fixed value of a parameter
* initial value of a function
* time-varying value of a function (np.ndarray) (of which the first line is the set of initial values)
Overwitting one (initial value) with another (fixed value) could become complex to handle in termes of automatisation, and confusing.

Let's continue discussing this until we converge on a satisfying solution / strategy

**Comment by DaluS** [comment]
I agree with you, and see how it could be dangerous. 

Let's first be sure of the points we agree to deduce the shape from it. I'm going to write down the vision I have, buckle up it might be long :) (But I hope it's worth it !)

## Studying models, providing simulation
* The goal of the code is to provide a convenient tool for general studies of a model (equilibrium, basin of attraction, sensibility...) and practical trajectories
* There are four layers of field definition : 
    * `_def_fields` which are kind of everything in the world as a very basis
    * `_model_NAME` that choose : 
         * what variables/parameters exist in the model 
         * what are the links between these variables and parameters (the function) 
    *  `_model_NAME._PRESET` that replace values in `_def_fields` when needed  ONLY IF CALLED 
    * Manual introduction of parameters (typically with the cockpit)
* We do so because : 
    * `_def_field` allow cross-model communication and a common basis for everyone 
* A model is an ensemble of logical hypotheses, consistent together, creating a closed system. A model has no quantitative value in it, it is only logical elements. The study of a model is to see the coupled logics dynamics in a general way, the practical use of a model is to project this set of consistent logical assessment into a defined field of variable/parameters. In consequence, numerical values are not, and should not be inside a model. 
* Presets are inside the file of a model as indications from the author of relevant projections one can do on the model. 

## What are the fields ? What are the hypotheses ?

When creating a model, there is a first step : 
* Describing the system : what are the elements that exist inside ( all the variables ).  
Then there are linked by two type of equations : 
* Consistency equations (being sure that things don't appear or disappear for convenience but for good reasons) 
* Behavior equations (typically how humans behavior is according the the other fields variable)

These two steps are right now done on paper and not numerically. On a very long run, we might take a look at this, but clearly not for now. 

There are two different elements we can call :
**The parameters** that are not going to move in time. **The variables** that will indeed evolves in time.

In the variables, there are different types also : 
* **The differential type** Which are not defining the variables but only their evolution
* **The state type** Which are consequence of the state of the system. They are depending of other state type variables, and of differential variables. In consequence they could all be expressed through differential one, but it is convenient to keep them explicit and calculated them. Their are witness/symptom of the state of the system, not the state of the system itself. 
* **auxilliary variables** (can be differential or state) are not used directly nor indirectly in the definition given by the user. In fact, auxilliary variables are a consequence of the way the user write the differential equations. Example : 

'''
g = (1 - \omega )/ \nu - \delta in goodwin model 
If we use : 
\dot{\lambda} = \lambda ( g - \alpha - \beta ) then g is an intermediary variable 
\dot{\lambda} =  \lambda ( (1 - \omega )/ \nu - \delta - \alpha - \beta ) then g is an auxilliary variable 
'''

The  modeller should not be the one who determine  the auxilliary equations in fact, the systemn can do it by itself.

The two types of equations are links between variables, that are done through parameters and variables.

**Comment by DaluS** [comment]
Done !
