### ISSUE TITLE
Incorporate intermediary function first steo into reset()

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#53]
Motivations:
----------------
* In PR #50, you introduced a method `Solver.runIntermediaryAtInitialState()` that computes the value of the intermediary functions for the first time step. I understand this can be useful for the user so when he/she print  a `Solver.get_summary()`, he/she will see the inital state not only for ode but for all time-varying quantities.
* I agree it is a good idea, and I propose to include this into the `Solver.reset()` method, as this method already sets the first time step of ode, it seems natural that it would set the first time step for everything.
* Also, it would minimize the number of different methods the user has to deal with.

Propose changes:
------------------------
* I will submit a PR incorporating the content of this method into `reset()`

**Comment by DaluS** [comment]
Done !
