### ISSUE TITLE
Implement additional solver for cross-checking + uncertainty

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#55]
Motivation:
--------------
* In #6, @DaluS identified that the convergence was not clear 
* We have implemented a home-made RK4 solver, which I think is very nice because it gives us the possibility of modifying and tweaking it as much as we want
* From my own experience, it always good to have easy access to at least 2 solvers, for cross-checking and for getting an idea of the amount of uncertainty on the results that depend on the choice of solver

Proposition:
----------------
* I propose to implement an option so the user can choose between our home-made custom solver a (set of?) ready-made one from scipy
* It will allow us to cross-check and might be helpful to debug the divergence spotted in #6 (especially since the scipy ones sometimes have good handling of numerical errors)
* It will allow the user the benchmark solvers to check the robustness of his numerical results and get an idea of the numerical uncertainty

**Comment by DaluS** [comment]
Now in #58
