### ISSUE TITLE
Differences between solvers

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#58]
Motivation:
--------------
* PR #57 showed a typical case in which the numerical behaviour depends on the solver chosen
* We need to understand these differences and, if possible, correct them (at leats for the homemade solver)

Example:
-------------
```
In [1]: import _core

In [2]: solH = _core.Solver('G_Reduced')
Suggested order for intermediary functions (func_order):
['pi', 'phillips', 'g']

In [3]: sol2 = _core.Solver('G_Reduced')
Suggested order for intermediary functions (func_order):
['pi', 'phillips', 'g']

In [4]: sol4 = _core.Solver('G_Reduced')
Suggested order for intermediary functions (func_order):
['pi', 'phillips', 'g']

In [5]: sol8 = _core.Solver('G_Reduced')
Suggested order for intermediary functions (func_order):
['pi', 'phillips', 'g']

In [6]: solH.run()
time step 10000 / 10000

In [7]: sol2.run(solver='eRK2-scipy')
The solver successfully reached the end of the integration interval.
Success: True
Nb. fev: 3004 for 10000 time steps (0.3004 per time step)

In [8]: sol4.run(solver='eRK4-scipy')
The solver successfully reached the end of the integration interval.
Success: True
Nb. fev: 6007 for 10000 time steps (0.6007 per time step)

In [9]: sol8.run(solver='eRK8-scipy')
The solver successfully reached the end of the integration interval.
Success: True
Nb. fev: 15016 for 10000 time steps (1.5016 per time step)

In [11]: k0 = 'lambda'

In [12]: plt.figure(); plt.plot(solH.get_dparam(returnas=dict)['time']['value'], solH.get_dparam(returnas=dict)[k0]['value'], '-k', label='homemade'); plt.plot(sol2.get_dparam(returnas=dict)['time']['value'
    ...: ], sol2.get_dparam(returnas=dict)[k0]['value'], '.r', label='scipy RK2'); plt.plot(sol4.get_dparam(returnas=dict)['time']['value'], sol4.get_dparam(returnas=dict)[k0]['value'], '.b', label='scipy R
    ...: K4'); plt.plot(sol8.get_dparam(returnas=dict)['time']['value'], sol8.get_dparam(returnas=dict)[k0]['value'], '.g', label='scipy RK8'); plt.legend(); plt.gca().axhline(0.97, c='k', ls='--'); plt.gca
    ...: ().axhline(0.94675, c='k', ls='--');
```
![image](https://user-images.githubusercontent.com/5929562/126490868-4e476993-ff6e-4c86-8f8b-15e778832416.png)

**Comment by DaluS** [comment]
As said in the PR, 

Great !

The result is surprising at first ( RK2 behaving better than RK4 behaving better than RK8 etc...) I'll go deeper into that.

To do so I think the protocol would be 

* Get set_dparam to work with manual override
a. I think it is already working but I never did that
b. check if it handle array of parameters well
* Write convergence test on the timesteps / error of solvers

I assume the initial error of RK2 is smaller but the convergence is less efficient than the Rk4.

I plan toward the implementation of parameters modification in my work, will be back on this test once it's easy to do so

**Comment by DaluS** [comment]
Difference found. 

An rk4 is calculating 4 different rk1 sequentially, with a sequence going through all the variables each iteration. This one does 4 sequence of rk1 for each variable separately, hence it's a weird rk1.

**Comment by DaluS** [comment]
Also, the output of scipy solver is not consistent with the output of the existing "rk4", it needs to be changed ( the question of parrallelism solved also)
