### ISSUE TITLE
Choosing the system of equations

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#6]
Motivations:
----------------
* Currently the system of equations is chosen by setting a class, which is hard-coded in Main.py
* The use of classes is a good idea, but the user should probably not have to hard-code a choice.
* Instead, an input keyword argument would a more flexible option to make sure the user does not have to dig into the code, also:
    - it would allow to save the choice of equations to solve as an input parameter, for reproducibility
    - it would allow to test dynamically all possible systems of equations from automated unit tests, which is not possible / much more complicated if the module has to be edited

**Comment by DaluS** [comment]
I totally agree. How would you do that ? string keyword then SYS determined in an if loop depending of the string input ? 

I think a lot of these "specificity" is that I only run my code through in Ipython terminal, so I mostly change the code inside then run some parts of it. A more classic workflow on my side could help

**Comment by DaluS** [comment]
Should I write here or in the pull request ? The message ( initially in the pull request) 

**About dictionnaries**

I really like your system, especially the way you plot it. It's an alternative/complement to what I've done with 'VariableDictionnary.py' (Which is for variables and plots)

* I would add in this dictionnary a way to define the same type of notation for variables (as done in 'VariableDictionnary.py'
* I would do a fusion between yours and my approach in 'VariableDictionnary.py' , adding a name column, and a category 'parameter' and 'variable' maybe on top of it ? 
* For the python-user, I would reduce what are inside these "megadictionnary" to only relevant variables/parameters (I've done a ugly but working version at the end of 'VariableDictionnary.py' ) 
* I would print numerical parameters in a separate section of the print
* I would use these informations inside the plots also to automatically generate them
* I saw that you define variables in '_def_variables.py' for each class. The names of variables are already defined in the class ( in 'self.variables' for each), no need to redefine each time for each module.

**About restructuration** I tried to integrate what you've done in your code, but I think I would do it badly (I think you haven't finished comments and added to many functions that I could understand at once) so I let you finish the integration ! 

**In the meantime** I will work on the integration of new modules ( plots and set of equations )

**Comment by Didou09** [comment]
As a reminder: I will deal with this issue (cf. PR #10  that was a first step) and then deal with issue #3 , but not today, probably sometime next week (sorry, presenting at a conference today)

**Comment by DaluS** [comment]
This is still an issue I have found no elegant solution ( I talk about it in #28 which would be the right place to talk about I guess)

**Comment by DaluS** [comment]
Issue solved with the new architecture !
