### ISSUE TITLE
First non-regression tests

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#64]
Motivations:
--------------
* Since PR #62 we now have a simple mechanism to save output data and to check whether 2 instances are identical
* The basis are now available to start implementing non-regression tests (non-regression in terms of output data)
* Principle: we include a set of reference output, for all models and solvers in the unit tests, and we use them to check that the output does not change as the code evolves (to make sure we did not introduce a bug)
* If the output changes for a good reason (e.g.: because we introduced an improvement in the accuracy / stability of a solver), the unit tests will fail (which will indicate the improvement is significant), and we will simply update the reference output.

Proposition:
--------------
* create a output_ref/ folder in the unit tests to hold the reference output, and use it for checking

**Comment by DaluS** [comment]
They are coded, but the system is not ready yet (solvers not working properly). This will be reactivated once #58 is done.
