### ISSUE TITLE
Identify articles to reproduce

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#7]
Motivations:
----------------
* We probably want to be able to reproduce the state of the art
* We probably want to include the reproduction of this state of the art into unit tests

@DaluS do you think you and @guittcam can take care of identifying the articles in questions, if you agree ?

Proposition:
-----------------
A possibility would be to create a `_articles.py` file in the repo, and create a dictionnary of references in it, each reference storing its own set of model parameters.

This can be used as a source of tabulated info and we can then think about to integrate this into unit tests and the solver itself (in a separated dedicated issue)

(feel free to close the issue if not relevant, and to discuss / comment if you think about better options)

**Comment by DaluS** [comment]
I have put a non-exhaustive list in the section projects !
