### ISSUE TITLE
List of Unit test that should be added 

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#81]
Motivations:
----------------
* PR #72 introduced the following new routines / methods:
    - `Hub.FindCycles()`
    - `Hub.FillCycles()`
    - `Hub.FillCyclesForAll()`

But it did not introduce the corresponding unit tests
The corresponding unit tests should be introduced

**Comment by DaluS** [comment]
Yes ! 
Also, need to rewrite the test for : 
* Changing parameters value
* Changing presets 
* Changing the number of system (not implemented yet)

About fields loading : 
* Loading fields
* Overloading fields
* Defining fields in the model and not in the library
* Calculation of parameters
* Calculation of function order
* Calculation of dimensional groups of variables 

About plots : 
* Automatic individual plots (with and without cycles) for each variables
* Automatic phasespace
* Automatic groups plots

**Comment by DaluS** [comment]
Transformed into : 
Newtests issue
