### ISSUE TITLE
_plot.AllVar() misbehaves a bit

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#84]
Motivations:
----------------
* The new routine `_plot.AllVar()` seems to not behave the way it is supposed to
* In particular: 
    - the argument `rows` has the wring name: it is in reality the number of columns
    - When the number of columns (`rows`) is increased, the a large blank space is left at the bottom of the figure

![image](https://user-images.githubusercontent.com/5929562/128760050-0823f8d7-b072-4ff3-bf1a-f8b01804bad1.png)

Proposition:
---------------
* Introduced the `matplotlib.gridspec` sub-library that gives more detailed control over that type issues
* Rename `rows` to `ncols` (the way it is called in `gridspec`)
* Make the whole space of the figure is used
* use `axes` and `figure` handles instead of `plt` for more control

**Comment by DaluS** [comment]
Oh excellent ! I didn't knew indeed about gridspec, I'll implement this in a new PR. I'll also replace the variable name with the symbol and latex in it

**Comment by DaluS** [comment]
Included in PR, thanks !
