### ISSUE TITLE
Incorrect units

### ISSUE THREAD

**Issue by MattArran** [DaluS/GEMMES#85]
In `_def_fields.py`, Some units are incorrect (e.g. wages are 'Dollars' rather than 'Dollars per human per year'), unconventional (e.g. years are 'y' rather than 'yr'), or inconsistent with the unit list (e.g. 'Dollars' rather than '$')

```      
        'alpha': {
            'value': 0.02,
            'definition': 'Rate of productivity increase',
            'units': 'y^{-1}',
        },
        'W': {
            'value': 0.85,
            'definition': 'Wage value',
            'units': 'dollars'
        },```

**Comment by DaluS** [comment]
You're right, I'll update y to yr, introduce `w` as wage per person ( and `W=wL` as usually found in litterature), yet I'm not sure about "$" I have to double-check with latex prints on figure how it'll behave. But I agree that it would be better
