### ISSUE TITLE
Reviewing PR #75 #76 #79

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#87]
Motivation:
---------------
* PR #75, #76, #79 introduce new formalism and several other changes
* They are big (30 files changed)
* I need a bit of time to review it all seriously, to do so I will:
        - copy the branch on my local
        - Go through your changes one by one, to understand exactly what is done
        - If necessary, propose small changes to make sure it passes unit tests (so you don't have to do it)
        - If necessary update the unit tests
* If I have small changes to suggest I will propose them through a PR that will be a duplicate of #75, with a  few differences (so I don't affect your PR, which is preserved as such, and you can choose which one you want to merge)

Starting today

**Comment by DaluS** [comment]
Super cool ! 
Do not hesitate to contact me anytime if something is unclear. I was thinking about restructuring a bit this part to make future add easier ( especially the conditions on "ode" "statevar" or the autofill which exist at multiple places ), I'm eager to discuss about it if you like !

**Comment by Didou09** [comment]
Today I only had ~2 hours this morning, so I won't be available in ~5 min (my girlfriend just woke up, breakfast time together :-))

But maybe we can arrange a short visio tomorrow morning ? somewhere between 08h30-11h ? Since I am on holidays I try to work only while she sleeps.

First quick question already:
--------------------------------------
From reading the new model files, I understand there is no `auxiliary` function anymore, they are included as `statevar` together with the former `intermediary` functions right ?
If you don't have time to answer we can discuss it tomorrow (or later)

I estimate I will need a few days to finish the review of those PR. 
Maybe a full week depending on my availability, is that timeline fine for you ?

P.S.: I read the presentation you gave on 08.08.2021 (I downloaded the slides / ipynb), I'm ok with everything you presented :-)

**Comment by DaluS** [comment]
I hadn't seen this message, sorry ! 
I "removed" auxilliary because it's far from priority (it will be useful when spatial PDE or a way more variables than what we have right now), I tried not to remove the code but simply comment/not update it. It'll be great to develop it again as we add PDE into the code

**Comment by DaluS** [comment]
Here it is ! That quite long issue is now fixed, thanks again @Didou09 !
