### ISSUE TITLE
Code-independent additions from PR #75, #76, #79

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#89]
In the process of reviewing PR #78, #76, #79, I realised that many chenged files actually do not affect the code itself.

In particular, it is the case of all changes to README, ypnb, tutorials...

I will group these changes in a single code-independent PR, which should make it easier to then focus on the parts that do change the code.

**Comment by DaluS** [comment]
Yes ! That looks good :)

**Comment by Didou09** [comment]
Done in PR #90  that you merged already
