### ISSUE TITLE
Error messages in def fields does not correspond to error

### ISSUE THREAD

**Issue by DaluS** [DaluS/GEMMES#94]
If I introduce a new unit in `__DEFAULTFIELDS` `units` `allowed`, then the system is raising me an error of type : 
![image](https://user-images.githubusercontent.com/11523050/130196876-cbaf67ab-b111-42d1-885b-728a4e307a5a.png)

There might be a message update missing in the checks

**Comment by Didou09** [comment]
Could you give more details so I can reproduce the error ?
a snpashot of the code you added in _def_fields.py ? What you did exactly ?
If I can reproduce it I'll fix it

**Comment by DaluS** [comment]
I tested with both `GK` and `G_Reduced`, with any position and name of variable to be added and it raise me this issue (so it goes well on your side and not on mine). 
I have to move right now but I'll check deeper tonight !

**Comment by Didou09** [comment]
OK, don't hesitate to send more info so I can help, did you do the same thing as I show above or did you do other things ?

This error comes from `_class_check._update_func_default_kwdargs(),` which updates default values of keyword arguments of functions.

Before doing so it checks that all input keyword args are unique

The error suggests that function `phi0` has 0 or several times the argument `phinull`

A priori, this has nothing to do with units.

Are you sure you did not do something else that just add a new unit ?

**Comment by DaluS** [comment]
The error does not appear anymore ! I close the issue.
No idea what created it, I had done specifically a test with a branch newly created yesterday, but this is no longer a problem
