### ISSUE TITLE
 `get_summary` possibilities of improvement

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#98]
So, shall we add it ?

**Comment by DaluS** [comment]
I agree ! 
I think it could be great to propose two sets of information in `get_summary` that the user could choose to load. 
Or an alternative, propose subcategories in `get_summary` as you did in `printDFIELDS`, either as the type of equations (parameters, statevar, ode...) or by group. This remove one column and give a better structure :)

Writing units could be done a better way as there is a dictionnary version ! I was thinking of a matrix formalism (as it is done in exercises to find dimensionless number and application of Pi-Buckingham theorem) that could remove some place also (and put the info in a specific place)

* function
* source
* initial
* final
* units
* eqtype
* definition 
* comment
* group
